<template>

  <div class="tourism_s">
    <v-header v-bind:bactive="bactive" v-bind:bheader="bheader"></v-header>
    <div class="tours_con">
      <img src="../../../static/images/t_banner1.png" alt="">

      <div class="charm_t">
        <div class="charm_title">
          <span><img class="triangle" src="../../../static/images/triangle.png" alt="">旅游攻略</span>
          <p class="address">当前位置：首页>旅游攻略><span>详情介绍</span></p>
        </div>

        <div class="tour_artile">
            <h6>旅游攻略</h6>
            <div class="section">
              <p>一、景区简介</p>
              <p>泸沽湖属国家级重点风景名胜区，国家AAAA级旅游景区，是中国第三深的淡水湖，湖面海拔2690米，水域面积58.8平方公里，平均水深45米，最大水深93米，能见度12米，是我国最清澈的高原湖泊之一。湖中有五个岛屿，湖岸有四个半岛和一个长岛，形态各异、引人入胜。15000亩的草海湿地是水生植物的王国和动物的乐园。湖畔的摩梭人至今仍保持着古老的“母系大家庭”和神秘的“走婚”习俗，被专家学者誉为“人类母系氏族社会活化石”和“世界最后的女儿国”；也是香格里拉旅游大环线的集散地;在美国学者约瑟夫•洛克的眼里她是一个“适合神仙居住的地方”。</p>
            </div>
            <div class="section">
              <p>二、旅游线路：</p>
              <p>西昌→盐源→泸沽湖 （258公里）</p>
              <p>攀枝花→泸沽湖  （230公里）</p>
            </div>
            <div class="section">
              <p>三、精彩不容错过：</p>
              <p>1.盛夏时节游草海：15000亩的草海是动植物的乐园，每当盛夏的时候水草葱郁，一片碧绿，划乘猪槽穿梭其间，听远处传来优扬的《啊哈巴拉》别有一番情趣。现已查明泸沽湖流域有种子植物784种，水生管束植物37种，极具特色的菠叶海草花蔓生于湖弯水中，管束细茎由水底扶摇而上在碧绿的湖面绽放一片洁白的小花，灿若碧空繁星，被诗人称为“女儿国中女儿花”。</p>
              <p>2.泸沽湖的秋天是最美的季节，层林尽染五彩斑斓，到处盛开着鲜艳的什洋锦花，是喜欢摄影的朋友不容错过的最佳季节。</p>
              <p>3. 泸沽湖水草茂密，鱼虾丰硕，成为种类繁多的水鸟栖息繁衍的天堂，每到冬季有天鹅、黑颈鹤、白尾海雕等多种珍禽在此处越冬，群鸟在湖面嬉戏，是观赏水鸟的最佳时机。如果偶遇下雪更是一番别样的景色。</p>
              <p>4. 节日</p>
              <p>（1）春节：春节期间泸沽湖各村都会举办一些传统的活动，如成丁礼、晒佛、舞狮等活动，是了解摩梭民俗文化的最好时机</p>
              <p>（2）转山转海节：每年的农历七月十五泸沽湖都有盛大而隆重的转山转海节，节日当天摩梭人要穿着最艳丽的服装，从各自的村落云集于格姆山下参加原始的宗教祭祀活动；民俗歌舞表演；各村组织的划船、织花腰带等比赛；最为盛大的篝火晚会。节日当天，是摩梭男女结交阿夏的最好时机，也是摩梭人的狂欢节和情人节。</p>
<p>（3）喇嘛节：于每年的冬月十二日至十五日举行，期间要举行喇嘛集体诵经、晒佛、跳格尔、巴俄舞等活动，祈祷神灵、降伏魔王，很多善男信女不远万里前来朝拜。期间也会吸引许多商贩前来摆摊设点经销各种商品，也是一次盛大的民间商品交易会。</p>
            </div>
            <div class="section">
            <p>四、地方特产</p>
            <p>泸沽湖有青娜油、各种野生菌、银鱼、湖虾、花椒等地方特产</p>
          </div>
            <div class="section">
            <p>五、餐饮、住宿及其他</p>
              <p> 泸沽湖的美食颇多，最有特色的莫过于猪膘肉、湖鱼、各种野生菌、咣当酒、苏理玛酒及走婚桥边的烤鸭蛋等特色烧烤。在泸沽湖镇上有多家餐厅，以及各宾馆、客栈的餐厅都可品尝到这些美食。</p>
<p>目前景区接待住宿床位4500多个，其中拥有四星级酒店一家、二星级酒店一家、星级农家乐十六家，基本上可以满足不同需求的游客。</p>
<p>较大的汽车修理厂有两家，位泸沽湖镇。汽车修理厂急救电话：0834-6390080；13734982386</p>
<p>景区内汽车加油站位于景区收费站旁，电话：0834-3078607</p>
          </div>
          <div class="section">
            <p>六、门票及其他费用：</p>
            <p>1、景区门票为100元/人；</p>
            <p>持学生证、60～69岁老年证、残疾证者50元/人；</p>
            <p>持役军人证、军残证、70岁以上老年证、国家新闻总署记者证免票</p>
            <p>2、其他费用</p>
            <p>划船：视距离远近30～200元/人</p>
            <p>摩梭家访：20元/人</p>
            <p>王妃故居：10元/人</p>
            <p>杨二车娜姆博物馆：28元/人</p>
            <p>篝火晚会：30元/人</p>
          </div>
          <div class="section">
            <p>七、投诉电话：0834-6390322；6362125；96927</p>
            <p>报警电话：0834-6390110</p>
            <p>急救电话：0834-6390120</p>
            <p>咨询电话：0834-6390322</p>
          </div>
          <div class="section">
            <img src="../../../static/images/tourism_s1.png" alt="">
          </div>
        </div>
      </div>
    </div>

    <v-footer></v-footer>

  </div>
</template>

<script>
  import header from '@/components/common/header'
  import footer from '@/components/common/footer'
  export default {
    name: 'tourism_s',
    data () {
      return {
        bactive: 5,
        bheader: 1
      }
    },
    components: {
      'v-header': header,
      'v-footer': footer
    }
  }

</script>

<style scoped>
  .tours_con {
    width: 100%;
    position: relative;
    z-index: 1;
    background: linear-gradient(#045ebc, #7ebfe9);
    width: 100%;
    padding-bottom: 104px;
  }
  .tours_con img {
    width: 100%;
    height: 588px;
    display: block;
  }
  .charm_t {
    width: 1156px;
    height:100%;
    background: rgba(255, 255, 255, 0.6);
    filter: blur();
    margin: 0 auto;
    margin-top: -217px;
    padding: 0 28px;
  }
  .charm_title {
    border-bottom: 1px solid #fff;
    height: 44px;
    padding-top: 10px;
    width: 100%;
  }
  img.triangle{width: 7px;height: 12px;vertical-align: inherit;display: inline;margin-right: 14px;}
  .charm_title > span {
    float: left;
    color: #444444;
    font-size: 14px;
    line-height: 44px;
    border-bottom: 2px solid #1182e3;
    padding: 0 10px;
  }
  .address {
    color: #666666;
    font-size: 14px;
    float: right;
    line-height: 44px;
    padding-right: 10px;
  }
  .address > span {
    color: #1182e3;
    font-size: 14px;
  }
.tour_artile{
  height: 100%;
  padding: 27px 36px 70px 36px;
}
  .tour_artile h6{margin: 0;font-size: 18px;color: #444444; margin-bottom: 15px}
  .section{margin: 16px 0}
  .section p{text-indent: 2em;font-size: 14px;color: #222222;line-height: 30px;}
  .section img{
    width: 680px;
    height: 450px;
    margin: 30px auto;
  }
</style>
