<template>
  <div class="travel_s">
    <v-header></v-header>
    <div class="tours_con">
      <img src="../../../static/images/t_banner1.png" alt="">

      <div class="charm_t">
        <div class="charm_title clearfix">
          <span> <img class="triangle" src="../../../static/images/triangle.png" alt="">旅游日志</span>
          <p class="address">当前位置：首页>旅游攻略><span>旅游日志</span></p>
        </div>

        <div class="tour_artile">
          <div class="author">
            <img src="../../../static/images/author.png" alt="">
            <span class="name">一直在路上</span>
            <span>2018-05-20</span>
            <img class="eye" src="../../../static/images/eye.png" alt="">
            <span >524</span>
            <span class="title">云南必游｜写给泸沽湖的一纸情书：爱你如初，情深一往</span>
          </div>
          <div class="section">
            <p>由于我在泸沽湖逗留的时间非常有限，满打满算也就只有3天时间。不幸的是，其中一天的天气状况并不好，天气阴沉寒冷准备起风，因此那天没有选择继续租车环湖，而是留在了里格村和里格半岛随便逛逛，以休息为主。所以下面写到的拍摄点主要以我本人亲身游历过的有限景点，也许我个人看到和了解到的信息并不全面，但还是希望对有心要收集这方面信息的人有些许的帮助。</p>
            <p>泸沽湖全景只有2个地方可以看到，一个是在从丽江进入泸沽湖景区大门的观景空地；另一个是狮子山山顶。</p>
            <p>狮子山山顶我没有坐缆车上去看过，但是丽江进泸沽湖景区大门的空地前，拼车师傅留了20分钟左右时间给我们拍照和观赏。到达全景观景地的时候，已经是接近中午12点了，所以光线非常地猛烈，顶光难拍照是肯定的，但是不拍就错过了，打后几天我们进入景区后在湖畔的各个区域活动，都无法看到泸沽湖的全景，所以这次最算是顶光难拍也要拍下来。到达观景空地时，可以看到有一个小土坡，站在小土坡上拍湖，视角上湖面不会被压得这么扁平，另外，如果镜头够广的话，可以把心形的湖给拍出来。</p>
          </div>
          <div class="section">
            <img src="../../../static/images/strategy12.png" alt="">
          </div>
          <div class="section">
            <p>里格村</p>
            <p>（1）里格半岛观景台：里格半岛观景台应该是整个泸沽湖最出名的观景台吧。在观景台上对着里格半岛构图取景所拍出来的照片已经成了泸沽湖的明信片了。每次一提到泸沽湖，能搜到和看到的照片大多数是这个观景台所拍摄下来的里格半岛。</p>
            <p>里格半岛观景台对着东方，而且地理位置也相对较高，加上有里格半岛做前景，因此也是个看日出的好地点。还是同样的问题，群山围绕，日出的一刹那我们是无法看见的，要等待太阳从山后露出脸来，像我们冬日去拍日出，正常是早上8点左右是日出时间，但因为被山阻挡，差不多要8点15分左右才能看见太阳露出来，如果不幸当天还有厚云挨着山峦的话，那太阳越过山之后能否冲破云层就要看运气了。</p>
            <p>另外，到上午10点之后阳光开始猛烈，很多人说这个时间拍的照片除了天空是正常曝光之外，其余都是一片黑，这是因为背光，加上光比大，无论是拍人还是拍景都不适合，除非你的镜头前套上减光滤镜。下午在观景台则为顺光拍摄，但这对摄影人来说，顺光太平淡，哈哈。</p>
            <p>（2）里格半岛：我对里格半岛的感受是近看不如远观。</p>
          </div>

          <div class="section">
            <img src="../../../static/images/strategy13.png" alt="">
          </div>
          <div class="section">
            <p>环湖</p>
            <p>（1）杨二车娜姆博物馆：博物馆本身没有什么看，但它地理位置高，坐落在小落水，可以看到比较大片湖面，她家门前一边是云南，一边是四川，背后是格姆女神峰，对面就是泸沽湖，可谓占尽了位置优势。</p>
            <p>（2）女神湾（又称赵家湾）：这个一直被称为整个泸沽湖最佳的看日落地点，我觉得名不符其不实。说实话，要看日出或日落，所站的位置越高越好。但是女神湾却是一个地势极低的位置，站在女神湾的观景台上看到的还是高山群和湖水，无差别的前景，日落还是一样早早被群山挡住，我还期盼会有晚霞出现，结果什么都没有。倒是在沿着女神湾归途的山路上，在较高的路边拍到天空幻变成明橙、粉红、幽蓝的渐变的颜色，湖面有一只小船点缀，这里所看到的景象比在地势低的女神湾要出彩。</p>
            <p>（3）随机湖边：回来整理照片才发现，原来环湖那天不少照片都是在路边拍的，开着车一路上看风景，看到哪里觉得好看就停下来拍，没有明确必须要看到哪些景点，反而在路边几棵黄叶的银杏树吸引了我的注意，于是我们把车子停下来，甚至把电动车也入镜，作为拍照的元素，而原来标注的景点不少都被我们不小心错过了。如果游客觉得泸沽湖的所有景点都不能错过的话，最好是包车环湖，司机必定会把你带到每个景点。</p>
          </div>
          <div class="section">
            <img src="../../../static/images/strategy14.png" alt="">
          </div>
        </div>
      </div>
    </div>

    <v-footer></v-footer>

  </div>

</template>

<script>
  import header from '@/components/common/header'
  import footer from '@/components/common/footer'
  export default {
    name: 'travel_s',
    data () {
      return {}
    },
    components: {
      'v-header': header,
      'v-footer': footer
    }
  }
</script>

<style scoped>
  .tours_con {
    width: 100%;
    position: relative;
    z-index: 1;
    background: linear-gradient(#045ebc, #7ebfe9);
    width: 100%;
    padding-bottom: 104px;
  }
  .tours_con img {
    width: 100%;
    height: 588px;
    display: block;
  }
  .charm_t {
    width: 1156px;
    height:100%;
    background: rgba(255, 255, 255, 0.6);
    filter: blur();
    margin: 0 auto;
    margin-top: -217px;
    padding: 0 28px;
  }
  .charm_title {
    border-bottom: 1px solid #fff;
    height: 44px;
    padding-top: 10px;
    width: 100%;
  }
  img.triangle{width: 7px;height: 12px;vertical-align: inherit;display: inline;margin-right: 14px;}
  .charm_title > span {
    float: left;
    color: #444444;
    font-size: 14px;
    line-height: 44px;
    border-bottom: 2px solid #1182e3;
    padding: 0 10px;
  }
  .address {
    color: #666666;
    font-size: 14px;
    float: right;
    line-height: 44px;
    padding-right: 10px;
  }
  .address > span {
    color: #1182e3;
    font-size: 14px;
  }
  .tour_artile{
    height: 100%;
    padding: 27px 36px 70px 36px;
  }
  .author{height: 58px;line-height: 58px;padding: 10px 0;
    border-bottom: 1px solid #666666;}
  .author img{width: 58px;height: 58px;border-radius: 50%;display: inline;vertical-align: bottom;}
  .author span{padding: 0 13px;font-size: 16px;color: #666666;}
  .author span.name{color: #1182e3;}
  .author img.eye{vertical-align: inherit;height: 12px;width: 19px;margin-right: -10px;}
  .author span.title{color: #222222;font-weight: 700;padding-left: 30px;}
  .section{margin: 16px 0}
  .section p{text-indent: 2em;font-size: 14px;color: #222222;line-height: 30px;}
  .section img{
    width: 680px;
    height: 450px;
    margin: 30px auto;
  }
</style>
