<template>

  <div class="walk_s">
    <v-header v-bind:bactive="bactive" v-bind:bheader="bheader"></v-header>
    <div class="tours_con">
      <img src="../../../static/images/t_banner1.png" alt="">

      <div class="charm_t">
        <div class="charm_title">
          <span><img class="triangle" src="../../../static/images/triangle.png" alt="">行在泸沽湖</span>
          <p class="address">当前位置：首页>旅游攻略><span>行在泸沽湖</span></p>
        </div>

        <div class="tour_artile">
          <h6>行在泸沽湖</h6>
          <div class="section">
            <p>长途汽车</p>
            <p>长途客运</p>
<p>泸沽湖位于云南和四川的交界处，到达泸沽湖的唯一方式就是乘坐汽车。从四川和云南转车到泸沽湖都十分方便。从四川去，要到西昌转汽车，从云南去的话要从丽江转汽车，车程6到7个小时不等。</p>
          </div>
          <div class="section">
            <p>丽江到泸沽湖</p>
            <p>丽江到泸沽湖可以先到宁蒗县，再转车到泸沽湖，也可以直接坐班车到泸沽湖。</p>
            <p>丽江——宁蒗——泸沽湖</p>
            <p>丽江市区到宁蒗的班车很多，每个客运站都有，有的还出售丽江到泸沽湖的联票（购买联票后，不用到宁蒗另外买到泸沽湖的车票，建议在买票前问清这一点，买联票相对方便一些）。宁蒗到泸沽湖的车也很多，多数都是小面包车，车票约30元，终点站到洛水村（大洛水），如到里格岛，要加收5-10元，如果定的客栈在里格，可以在洛水村打电话给里格岛的客栈老板，大部分客栈会提供接人服务。</p>
            <p>丽江——泸沽湖</p>
            <p>丽江已经开通直达泸沽湖的班车，约往返140元/人，但车次较少，每天早上9:30左右发车,终点是到洛水村。直接坐车到泸沽湖的，建议提前一天到客运站咨询、买票。</p>
          </div>
          <div class="section">
            <p>西昌到沪沽湖</p>
            <p>西昌汽车旅游客运中心有直接到泸沽湖镇的班车，票价75元左右，全程265公里，车程约7个小时，每天一班，早上8:00左右发车，节假日会增加班次（具体发车时间和班次建议咨询当地客运站），班车终点站是四川泸沽湖的泸沽湖镇（即左所镇）。 </p>
            <p>Tips</p>
            <p>客运站一般早上5:30卖票，去泸沽湖建议提前购票，避免当天买不到票的情况。泸沽湖回西昌的班车不多，由于当地是承包制，每天的车落到每一家头上，所以回程的时候需要提前去镇上咨询今天是哪家的车，提早买票。一般回程班车走的时间较早，要提前做好准备。</p>
            <p>西昌汽车旅游客运中心</p>
            <p>地址：西昌市三岔口南路412号（近航天大道）</p>
            <p>联系方式：0834-3082318</p>
            <p>到达交通：西昌火车站乘坐12路公交车可到</p>
          </div>
          <div class="section">
            <p>租车</p>
            <p>泸沽湖游玩包车是比较方便的方式之一，如果是一个人旅行，可以向客栈老板打听一下，一般他们能帮你找到一起包车的人。依据车型、季节、旅游线路的不同，包车的价格也不同，价格一般在400-600元/天/车左右。</p>
          </div>
          <div class="section">
            <p>其他</p>
            <p> 乘船&骑马</p>
           <p>泸沽湖景区内可坐猪槽船游湖，也可以骑马，船和马由当地的摩梭村寨集体所有，统一经营，统一价格，所有收入均由摩梭村集体分配，价格视距离远近费用在30-200元/人不等。如要乘船从四川泸沽湖前往云南泸沽湖船费为80元/人，从云南泸沽湖乘船到四川泸沽湖船费为120元/人。泸沽湖的码头很多，基本上各个靠湖的村落都有码头，也都可以坐船到附近景点游玩，码头分布如下：</p>
           <p>草海附近：五支洛码头、博树码头、扎俄洛码头和洛洼码头</p>
           <p>女神湾：女神湾码头</p>
           <p>洛洼：洛洼码头</p>
           <p>达祖村（大嘴村）附近：达祖码头、洼垮码头</p>
           <p>里格半岛：里格码头</p>
           <p>大洛水附近：洛水码头、泸沽湖游湖码头、小渔坝码头、三家村码头</p>
           <p>坐船至各景点价格（参考）:</p>
           <p>里格——里格湾：10元/人</p>
           <p>里格——鸟岛：30元/人</p>
           <p>里格——湖心岛（媳娃娥岛）：35元/人</p>
           <p>里格——小洛水：40元/人</p>
           <p>里格——大洛水：45元/人</p>
           <p>里格——达祖村（大嘴村）：60元／人</p>
            <p>小洛水——王妃岛：30元/人</p>
            <p>小洛水——里务比岛：40元/人</p>
            <p>小洛水——王妃岛——里务比岛： 45元/人</p>
            <p>骑马至各景点价格（参考）：</p>
            <p>小洛水——走婚桥：20元/人</p>
            <p>里格——尼塞村：30元/人</p>
            <p>里格——小洛水：40元/人</p>
            <p>里格——竹地：30元/人</p>
            <p>里格——月亮湖：60元/人</p>
          </div>

        </div>
      </div>
    </div>

    <v-footer></v-footer>

  </div>
</template>

<script>
  import header from '@/components/common/header'
  import footer from '@/components/common/footer'
  export default {
    name: 'walk_s',
    data () {
      return {
        bactive: 5,
        bheader: 1
      }
    },
    components: {
      'v-header': header,
      'v-footer': footer
    }
  }

</script>

<style scoped>
  .tours_con {
    width: 100%;
    position: relative;
    z-index: 1;
    background: linear-gradient(#045ebc, #7ebfe9);
    width: 100%;
    padding-bottom: 104px;
  }
  .tours_con img {
    width: 100%;
    height: 588px;
    display: block;
  }
  .charm_t {
    width: 1156px;
    height:100%;
    background: rgba(255, 255, 255, 0.6);
    filter: blur();
    margin: 0 auto;
    margin-top: -217px;
    padding: 0 28px;
  }
  .charm_title {
    border-bottom: 1px solid #fff;
    height: 44px;
    padding-top: 10px;
    width: 100%;
  }
  img.triangle{width: 7px;height: 12px;vertical-align: inherit;display: inline;margin-right: 14px;}
  .charm_title > span {
    float: left;
    color: #444444;
    font-size: 14px;
    line-height: 44px;
    border-bottom: 2px solid #1182e3;
    padding: 0 10px;
  }
  .address {
    color: #666666;
    font-size: 14px;
    float: right;
    line-height: 44px;
    padding-right: 10px;
  }
  .address > span {
    color: #1182e3;
    font-size: 14px;
  }
  .tour_artile{
    height: 100%;
    padding: 27px 36px 70px 36px;
  }
  .tour_artile h6{margin: 0;font-size: 18px;color: #444444; margin-bottom: 15px}
  .section{margin: 16px 0}
  .section p{text-indent: 2em;font-size: 14px;color: #222222;line-height: 30px;}
  .section img{
    width: 680px;
    height: 450px;
    margin: 30px auto;
  }
  >>>p img{
       width: 680px;
       height: 450px;
       margin: 30px auto;
       margin-left: 200px;
     }
</style>
